server:
  port: 8083

spring:
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
      sort:
        sort-parameter: sort
  application:
    name: vacancy-service

  datasource:
    url: jdbc:postgresql://localhost:5432/devmatch_vacancy
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

jwt:
  secret: /twA7/Xxl4oC3WNBty3wNL94d/+4/mehRhkatN5lblI=