server:
  port: 8888

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**
        - id: vacancy-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/vacancies/**
    config:
      enabled: false
      import-check:
        enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

jwt:
  secret: /twA7/Xxl4oC3WNBty3wNL94d/+4/mehRhkatN5lblI=
